#!/bin/bash
# Get RAM usage percentage
# Output: single number (0-100)

# Read memory info
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')

# Calculate used percentage
if [[ $mem_total -gt 0 ]]; then
    mem_used=$((mem_total - mem_available))
    usage=$((mem_used * 100 / mem_total))
    echo "$usage"
else
    echo "0"
fi
