#!/bin/bash

printf "[general]\nframerate=20\nbars = 46\n[output]\nmethod = raw\nraw_target = /dev/stdout\ndata_format = ascii\nascii_max_range = 70\nchannels = mono\nnoise_reduction = 0\n" | cava -p /dev/stdin
