#!/bin/bash

exec cava -p /dev/stdin <<'CAVA' | sed -u 's/;$//; s/;/,/g' | awk '{print "[" $0 "]"; fflush()}'
[general]
framerate=60
bars=51
[output]
method=raw
raw_target=/dev/stdout
data_format=ascii
ascii_max_range=100
channels=mono
noise_reduction=0.5
CAVA
