#!/bin/bash

STATE="/run/user/1000/eww_cpu_graph"
LINES=51

awk -v state="$STATE" -v lines="$LINES" '
BEGIN {
    has_prev = 0
    hist = ""
    if ((getline < state) > 0) {
        prev_user = $1 + 0; prev_nice = $2 + 0; prev_idle = $3 + 0
        if ((getline hist < state) > 0) {}
        close(state)
        has_prev = 1
    }
    if (hist == "") {
        hist = "0"
        for (i = 2; i <= lines; i++) hist = hist ",0"
    }
}
/^cpu / {
    user = $2 + 0; nice = $4 + 0; idle = $5 + 0

    if (has_prev) {
        u1 = prev_user + prev_nice
        t1 = u1 + prev_idle
        u = user + nice
        t = u + idle
        dt = t - t1
        if (dt > 0) {
            du = u - u1
            if (du < 0) du = 0
            pct = int(du * 100 / dt)
        } else {
            pct = 0
        }
    } else {
        pct = 0
    }

    sub(/^[^,]+,/, "", hist)
    hist = hist "," pct

    printf "[" hist "]\n"

    print user, nice, idle > state
    print hist > state
    close(state)
}
' /proc/stat