#!/bin/bash

declare -r NET_PATH="/run/user/1000/eww_net"

convert_bytes() {
    local bytes=$1
    local unit="B"
    if ((bytes >= 1073741824)); then
        unit="GB"
        bytes=$(bc <<< "scale=2; $bytes / 1073741824")
    elif ((bytes >= 1048576)); then
        unit="MB"
        bytes=$(bc <<< "scale=2; $bytes / 1048576")
    elif ((bytes >= 1024)); then
        unit="KB"
        bytes=$(bc <<< "scale=2; $bytes / 1024")
    fi

    echo "$bytes $unit"
}


IFS=" "
up=0
down=0
if [[ -f "${NET_PATH}" ]]; then
    read -r up down < "${NET_PATH}"
fi

read -r new_down new_up <<< $(cat /proc/net/dev | awk 'NR==4 {printf "%s %s", $2,$10}')


echo "{ \"down\": \"$(convert_bytes ${new_down})\", \"up\": \"$(convert_bytes ${new_up})\", \"speed_down\": \"$(convert_bytes $((new_down - down)))\", \"speed_up\": \"$(convert_bytes $((new_up - up)))\" }"

echo "$new_up $new_down" > "${NET_PATH}"
