#!/bin/bash

nmcli -g NAME,TYPE,DEVICE c 2>/dev/null | awk -F: '
BEGIN {
    icons["vpn"] = "󰒘"
    icons["802-3-ethernet"] = "󰈀"
    icons["wifi"] = "󰖩"
    icons["802-11-wireless"] = ""
    icons["bluetooth"] = ""
    icons["bridge"] = "󰡨"
    icons["tun"] = "󱠾"
    icons["wireguard"] = "󰠥"
    printf "["
}
$2 != "tun" && $2 != "bridge" && $2 != "loopback" {
    name = $1
    type = $2
    device = $3
    status = device == "" ? "off" : "on"
    icon = (type in icons) ? icons[type] : ""
    if (sep) printf ","
    printf "{\"name\":\"%s\",\"type\":\"%s\",\"status\":\"%s\"}", name, icon, status
    sep = 1
}
END { printf "]\n" }'