#!/bin/bash

declare -A icons=(
    ["vpn"]="󰒘" # 󰒙
    ["802-3-ethernet"]="󰈀"
    ["wifi"]="󰖩" # 
    ["802-11-wireless"]="" # 
    ["bluetooth"]=""
    ["bridge"]="󰡨"
    ["tun"]="󱠾"
    ["wireguard"]="󰠥"
)
entries=()
while IFS=':' read -r name type device; do
    [[ $type == @(tun|bridge|loopback) ]] && continue

    if [[ -z $device ]]; then
        status="off"
    else
        status="on"
    fi

    # Используем иконку по умолчанию если тип не найден
    icon="${icons[$type]:-}"

    # Формируем JSON-объект
    printf -v entry '{"name":"%s","type":"%s","status":"%s"}' \
        "$name" "$icon" "$status"
    entries+=("$entry")
done < <(nmcli -g NAME,TYPE,DEVICE c 2>/dev/null)

# Формируем итоговый JSON
IFS=','
printf "[%s]\n" "${entries[*]}"