#!/bin/bash

declare -r MPV_SOCKET="/run/user/1000/mpvsocket"
declare -r IMG_PATH="$HOME/.cache/eww"

function player_img() {
    local -r title=$(echo '{ "command": ["get_property", "media-title"] }' | socat - ${MPV_SOCKET} | jq .data | tr -d '"')
    local -r image_path="$IMG_PATH/$title.png"
    local -r path=$(echo '{ "command": ["get_property", "path"] }' | socat - ${MPV_SOCKET} | jq .data | tr -d '"')
    ffmpeg -ss "$1" -loglevel 0 -y -i "$path" "$image_path"
}

function pause() {

    declare -A player_commands=(
        ["mpv"]="'{ \"command\": [\"cycle\", \"pause\" ] }' | socat - ${MPV_SOCKET}"
        ["org.telegram.desktop"]="playerctl -p \"$1\" play-pause"
        ["plasma-browser-integration"]="playerctl -p $1 play-pause"
        ["mopidy"]="mopidy playpauseexit 0"
    )

    case "$1" in
        "mpv")
            local -r position=$(echo '{ "command": ["get_property", "time-pos"] }' | socat - ${MPV_SOCKET} | jq .data | tr -d '"' | cut -d'.' -f 1)
            if [[ $position != "" && $position != "Connection refused" ]]; then
                player_img "$position"
                ${player_commands[$1]}
                exit 0
            fi
            ;;
        "org.telegram.desktop" | "plasma-browser-integration" | "mopidy")
            ${player_commands[$1]}
            exit 0
            ;;
    esac

    exit 0
}

function position() {
    local -r duration=$(echo '{ "command": ["get_property", "duration"] }' | socat - ${MPV_SOCKET} | jq .data | tr -d '"' | cut -d'.' -f 1)
    if [[ $duration != "" && $duration != "Connection refused" ]]; then
        ((pos = $1 * "$duration" / 100 ))
        player_img "$(date -u -d @"$pos" +'%H:%M:%S')"
        echo "{ \"command\": [\"set_property\", \"time-pos\", $pos] }" | socat - ${MPV_SOCKET}
        exit 0
    fi

    length=$(playerctl --player plasma-browser-integration metadata -f '{{ mpris:length }}')
    if [[ -n $length ]]; then
        playerctl position $(( $1 * $length / 100000000 ))
    fi
    exit 0
}


case "$1" in
    "pause") pause "$2" ;;
    "position") position "$2" ;;
esac
