#!/bin/bash

# Финальная версия скрипта для получения информации о громкостях
data=$(pactl list sink-inputs | awk '
    BEGIN {
        num = ""; vol = ""; name = ""; reset_flag = 0
    }

    /Вход аудиоприёмника №[0-9]+/ {
        # Если есть предыдущие данные - выводим
        if (num != "" && vol != "" && name != "") {
            print num
            print vol
            print name
        }
        # Извлекаем номер потока
        num = $0
        sub(/.*№/, "", num)
        # Сбрасываем остальные переменные
        vol = ""
        name = ""
        reset_flag = 1
    }

    /Громкость:/ {
        if (reset_flag) {
            # Ищем процентное значение
            split($0, parts, " ")
            for (i in parts) {
                if (parts[i] ~ /[0-9]+%/) {
                    vol = parts[i]
                    sub(/%/, "", vol)
                    break
                }
            }
        }
    }

    /media.name =/ {
        if (reset_flag) {
            # Извлекаем имя приложения
            name = $0
            sub(/.*media.name = "/, "", name)
            sub(/".*/, "", name)
            reset_flag = 0
        }
    }

    END {
        if (num != "" && vol != "" && name != "") {
            print num
            print vol
            print name
        }
    }
')

# Если данных нет, возвращаем пустой массив
if [[ -z "$data" ]]; then
    echo "[]"
    exit 0
fi

# Читаем данные в массив
readarray -t array <<< "$data"

# Формируем JSON
json_items=()
for ((i=0; i<${#array[@]}; i+=3)); do
    num="${array[i]}"
    vol="${array[i+1]}"
    name="${array[i+2]}"

    # Пропускаем неполные записи
    [[ -z "$num" || -z "$vol" || -z "$name" ]] && continue

    # Экранирование спецсимволов
    name="${name//\\/\\\\}"
    name="${name//\"/\\\"}"

    # Формируем JSON элемент
    json_items+=("{\"num\":\"$num\",\"value\":\"$vol\",\"name\":\"$name\"}")
done

# Вывод результата
if [[ ${#json_items[@]} -gt 0 ]]; then
    echo "["
    for ((i=0; i<${#json_items[@]}; i++)); do
        if [[ $i -lt $((${#json_items[@]} - 1)) ]]; then
            echo "    ${json_items[$i]},"
        else
            echo "    ${json_items[$i]}"
        fi
    done
    echo "]"
else
    echo "[]"
fi