#!/bin/bash

# Скрипт для получения информации о громкостях
data=$(pactl list sink-inputs | awk '
    BEGIN {
        num = ""; vol = ""; name = ""
    }

    /Вход аудиоприёмника №[0-9]+/ {
        if (num != "") {
            print num
            print vol
            print name
        }
        # Извлекаем номер потока
        num = $0
        sub(/.*№/, "", num)
        vol = ""
        name = ""
    }

    /Громкость:/ {
        # Ищем процентное значение
        split($0, parts, " ")
        for (i in parts) {
            if (parts[i] ~ /[0-9]+%/) {
                vol = parts[i]
                sub(/%/, "", vol)
                break
            }
        }
    }

    /media.name =/ {
        # Извлекаем имя приложения
        name = $0
        sub(/.*media.name = "/, "", name)
        sub(/".*/, "", name)
    }

    END {
        if (num != "") {
            print num
            print vol
            print name
        }
    }
')

# Если данных нет, возвращаем пустой массив
if [[ -z "$data" ]]; then
    echo "[]"
    exit 0
fi

# Читаем данные в массив
readarray -t array <<< "$data"

# Формируем JSON (3 элемента на поток)
json_items=()
for ((i=0; i<${#array[@]}; i+=3)); do
    num="${array[i]}"
    vol="${array[i+1]}"
    name="${array[i+2]}"

    # Пропускаем неполные записи
    [[ -z "$num" || -z "$vol" || -z "$name" ]] && continue

    # Экранирование спецсимволов
    name="${name//\\/\\\\}"
    name="${name//\"/\\\"}"

    # Формируем JSON элемент
    json_items+=("{\"num\":\"$num\",\"value\":\"$vol\",\"name\":\"$name\"}")
done

# Вывод результата
if [[ ${#json_items[@]} -gt 0 ]]; then
    echo "["
    for ((i=0; i<${#json_items[@]}; i++)); do
        if [[ $i -lt $((${#json_items[@]} - 1)) ]]; then
            echo "    ${json_items[$i]},"
        else
            echo "    ${json_items[$i]}"
        fi
    done
    echo "]"
else
    echo "[]"
fi