#!/bin/bash

declare -a ARROWS=(
                   ''  # Штиль
                   'd' # Северный
                   'f' # Северо-восточный
                   'b' # Восточный
                   'e' # Юго-восточный
                   'c' # Южный
                   'g' # Юго-западный
                   'a' # Западный
                   'h' # Северо-западный
               )

function get_weather() {
    local -r type="$1"
    local -r params="$2"

    res=$(curl -H "X-Gismeteo-Token: $GISMETEO_TOKEN" "https://api.gismeteo.net/v2/weather/$type/4517/$params")

    echo "$res"  | jq .response

}


if   [[ "$1" == "now" ]];  then get_weather "current" ""
elif [[ "$1" == "day" ]];  then get_weather "forecast" "?days=2"
elif [[ "$1" == "week" ]]; then get_weather 'forecast/aggregate' '?days=5'
fi